import "./index.css";
import { Suspense, useRef } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, useGLTF } from "@react-three/drei";
import ModelLong from "./ModelLong";
import ModelSmall from "./ModelSmall";
import ModelStraight from "./ModelStraight";

// import Model2 from "./Model2";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HardBread (https://sketchfab.com/Alexey..Tverdohleb)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/railway-ca1cc6ea0ae84816882cf790cb980aec
title: Railway
*/






// https://github.com/CesiumGS/gltf-pipeline

/*
Ref: https://www.youtube.com/watch?v=xy_tbV4pC54

https://github.com/CesiumGS/gltf-pipeline: 

1. Converting a glTF to glb

  gltf-pipeline -i scene.gltf -o scene.glb

2. compress up to level 10:
 
 gltf-pipeline -i scene.glb -o scene_draco.glb --draco.compressionLevel=10

3. Genarate rxjs elements 

  npx gltfjsx fileName.glb
*/

// Change color : https://www.youtube.com/watch?v=2jwqotdQmdQ

function App() {
  return (
    <div className="App">
        <div className="wrapper">
            <Canvas>
                <Suspense fallback={null}>
                    <ambientLight/>
                    <spotLight intensity={1.2} angle={0.1} penumbra={1} position={[10,15,10]} castShadow/>
                    <pointLight intensity={0.9} position={[2,2,2]}/>
                    <ModelSmall position={[10, 0, -10]}>
                        <ModelStraight position={[10, 0, -10]}/>
                    </ModelSmall>
                    <OrbitControls enablePan={true} enableZoom={true} enableRotate={true} enabled={true}/>
                </Suspense>
            </Canvas>
        </div>
        </div>
  );
}

export default App;
