/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mike Polyakovich (https://sketchfab.com/MikePunisher)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/railway-a13366d35169465783d6c7e9e0c2f14d
title: Railway
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelSmall({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/RailwaySmall/scene_railsmall.glb')
    return (
        <group ref={group} {...props} dispose={null} scale={1}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[30, -20, 10]}>
                        <mesh geometry={nodes.m_Railway_mt_Railway_0.geometry} material={materials.mt_Railway}/>
                    </group>
                </group>
            </group>
        </group>
    )
}