/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Unreal Nick (https://sketchfab.com/lastnickleft)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rail-track-straight-99596461f679492bafe0ddc4a22fa1d0
title: Rail track straight
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelStraight({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/RailwayStraight/scene_straights.glb')
    return (
        <group ref={group} {...props} dispose={null} scale={1}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.pasted__pasted__group13_pasted__pasted__pasted__pCylinder3_screwsbase_0.geometry} material={materials.screwsbase} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.pCube6_woodbase_0.geometry} material={materials.woodbase} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.pCube7_rail_0.geometry} material={materials.rail} />
                    </group>
                </group>
            </group>
        </group>
    )
}