/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HardBread (https://sketchfab.com/Alexey..Tverdohleb)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/railway-ca1cc6ea0ae84816882cf790cb980aec
title: Railway
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelLong({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/RailwayLong/scene_rail.glb')
    return (
        <group ref={group} {...props} dispose={null} scale={3}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes['������������_����_0'].geometry} material={materials.material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes['������������������������������_����_0'].geometry} material={materials.material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes['����������_����_0'].geometry} material={materials.material} />
                    </group>
                </group>
            </group>
        </group>
    )
}
